### PR TITLE
Added ClassName and Namespace to CSharpGeneratorSettings

### PR DESCRIPTION
**Pull request by cpx86**
The ClassName and Namespace are currently auto-generated. It would be useful to be able to specify these explicitly in your cakefile, since the auto-generated pattern doesn't necessarily fit everyone's needs.

### CODE REVIEW

**Comment by agc93** [comment]
Just so I'm 100% clear, what is different here from simply specifying the Namespace and Class name by passing "MyProject.Namespace.Class"(or whatever) in the call to `ToCSharpClient`?

i.e. `NSwag.FromSwaggerSpecification("./swagger.json").ToCSharpClient("./client.cs", "MyProject.Namespace.Class");` for example?

**Comment by cpx86** [comment]
Ah, seems I was a bit quick on the buck there. I didn't notice that the only purpose of that parameter was to construct the namespace and class name. Closing this.

I have a related question though about the general design of the SwaggerSource class. Is there any specific reason why some NSwag settings are exposed via `Cake.NSwag.Settings.CSharpGeneratorSettings`, and some are exposed by explicitly providing an instance of `NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpClientGeneratorSettings`? Wouldn't it be more consistent and easier to maintain if it just used the original NSwag settings class for everything? It's especially confusing that even if you pass your own SwaggerToCSharpClientGeneratorSettings instance, some of the properties would be overwritten by the CSharpGeneratorSettings.

**Comment by agc93** [comment]
@cpx Fair question, and that was actually issue #1 from NSwag's creator himself when I first published this, and the short version is that when I first wrote it, I didn't do a good job of designing the settings classes 😆 

In reality, you're right, and the main advantage to the Cake.NSwag-specific ones is an insulating layer against breaking changes in the "core" settings. As it turns out, that's not really been much of an issue so if this library ever gets much traction, I will probably deprecate those settings in favour of the generic NSwag ones, and just rely on extension methods.

**Comment by cpx86** [comment]
@agc93 That's a perfectly valid explanation. Designing contracts is hard and designing contracts for third-party consumption is damn hard ;)

I'm not sure how much it counts as traction, but I'm currently evaluating using Cake for a number of CI builds, as well as NSwag for generating multiple API clients to be used by multiple consumers. So for me at least, shaping up the Cake.NSwag interface would make me a happy camper.

**Comment by cpx86** [comment]
@agc93 If you're interested, I could take a stab at deprecating the Cake.NSwag-specific settings classes and implement extension methods on the "core" settings classes instead. A "nice" solution for any users of the package out there could be to add Obsolete to the deprecated features and bump to v.0.5.0. Whenever this project reaches v1.0.0 the types and methods would be dropped. Or, just drop them straight away since the version is <1.0.0 which is considered unstable by SemVer anyway. That's up to you to decide as maintainer I guess :)

**Comment by agc93** [comment]
I'll need to do a basic release soon that will bump to 0.5.0 to upgrade NSwag to v6 and potentially fix that issue you were seeing that needs the `-experimental` flag. I'll look into it again then, and I'll either start deprecating there or if I'm short on time, I'll ping back here and you can have a crack 😄

**Pull request closed without merging**
